Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ricardo Adriano
// Descrição   : multiplos de um número
// Autor(a)    : Alexandre e joão
// Data atual  : 11/06/2022
Var
// Seção de Declarações das variáveis 
n, c: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("digite um número inteiro:" )
   leia(n)
   para c de 0 ate 9 passo 1 faca
    escreval(n, " x", c, " =", n*c)
   fimpara

Fimalgoritmo